Repository NethermindEth/dotnet-libp2p, pull requests merged in 2025-08, with the labels that each got.

#138 Fix Dockerfile
  src/samples/transport-interop/Dockerfile
Labels: bug

#140 (WIP) Add a generic protocol implementation over ISessionProtocol
  src/libp2p/Libp2p.Protocols.RequestResponse.Tests/Libp2p.Protocols.RequestResponse.Tests.csproj
  src/libp2p/Libp2p.Protocols.RequestResponse.Tests/RequestResponseProtocolTests.cs
  src/libp2p/Libp2p.Protocols.RequestResponse/Extension.cs
  src/libp2p/Libp2p.Protocols.RequestResponse/Libp2p.Protocols.RequestResponse.csproj
  src/libp2p/Libp2p.Protocols.RequestResponse/README.md
  src/libp2p/Libp2p.Protocols.RequestResponse/RequestResponseProtocol.cs
  src/libp2p/Libp2p.slnx
  src/libp2p/Libp2p/Libp2p.csproj
  src/samples/transport-interop/packages.lock.json
Labels: protocol

#141 Fix generation using protobuf generator nuget; clean up API
  README.md
  src/libp2p/Directory.Packages.props
  src/libp2p/Libp2p.Core.TestsBase/Libp2p.Core.TestsBase.csproj
  src/libp2p/Libp2p.Core/IPeerFactoryBuilder.cs
  src/libp2p/Libp2p.Core/Libp2p.Core.csproj
  src/libp2p/Libp2p.Core/PeerFactoryBuilderBase.cs
  src/libp2p/Libp2p.E2eTests/E2eTestSetup.cs
  src/libp2p/Libp2p.Generators.Protobuf/Libp2p.Generators.Protobuf.csproj
  src/libp2p/Libp2p.Generators.Protobuf/README.md
  src/libp2p/Libp2p.Protocols.PubsubPeerDiscovery.E2eTests/PubsubDiscoveryE2eTestSetup.cs
  src/libp2p/Libp2p.Protocols.PubsubPeerDiscovery/Libp2p.Protocols.PubsubPeerDiscovery.csproj
  src/libp2p/Libp2p.Protocols.RequestResponse.Tests/RequestResponseProtocolTests.cs
  src/libp2p/Libp2p.Protocols.RequestResponse/Extension.cs
  src/libp2p/Libp2p.Protocols.RequestResponse/README.md
  src/samples/chat/Program.cs
  src/samples/perf-benchmarks/Program.cs
  src/samples/transport-interop/packages.lock.json
Labels: refactoring
